# Generated by Django 5.2.9 on 2025-12-30 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('emp_type', models.CharField(choices=[('TEACHING', 'Teaching Staff'), ('NON_TEACHING', 'Non-Teaching Staff'), ('ADMIN', 'Administrative'), ('SUPPORT', 'Support Staff')], max_length=20)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('joining_date', models.DateField()),
                ('bank_account_no', models.CharField(max_length=50)),
                ('pan_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('UTILITY', 'Electricity/Water/Internet'), ('MAINTENANCE', 'Maintenance/Repairs'), ('PURCHASE', 'Assets/Inventory Purchase'), ('SALARY', 'Salary Payments'), ('EVENT', 'Event Expenses'), ('OTHER', 'Miscellaneous')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('receipt_url', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed')], default='PENDING', max_length=20)),
                ('payment_date', models.DateField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.employee')),
            ],
            options={
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
