"""
Centralized Constants for Y.S.M Education Management System
Prevents "Magic Numbers" and ensures consistency across the platform.
"""

# SUBSCRIPTION LIMITS
MAX_STUDENTS_COACHING = 1000
MAX_STUDENTS_SCHOOL = 5000
MAX_STUDENTS_INSTITUTE = 10000

SUBSCRIPTION_DAYS_DEFAULT = 30
TRIAL_DAYS = 7

# SECURITY LIMITS
MAX_FILE_SIZE_MB = 5
MAX_LOG_ENTRIES = 100
MAX_SEARCH_RESULTS = 50
MAX_REQUEST_SIZE_MB = 10

# AUTHENTICATION
OTP_EXPIRY_MINUTES = 10
SIGNATURE_VERIFICATION_THRESHOLD_MINUTES = 5

# RATINGS/LIMITS
BURST_RATE_LIMIT = "60/minute"
LOGIN_RATE_LIMIT = "10/hour"
PASSWORD_RESET_RATE_LIMIT = "5/hour"
PAYMENT_RATE_LIMIT = "20/hour"

# ROLES
ROLE_SUPER_ADMIN = 'SUPER_ADMIN'
ROLE_CLIENT = 'CLIENT'
ROLE_ADMIN = 'ADMIN'
ROLE_TEACHER = 'TEACHER'
ROLE_STUDENT = 'STUDENT'
ROLE_PARENT = 'PARENT'

# INSTITUTION TYPES
INST_TYPE_COACHING = 'COACHING'
INST_TYPE_SCHOOL = 'SCHOOL'
INST_TYPE_INSTITUTE = 'INSTITUTE'
INST_TYPE_UNIVERSITY = 'UNIVERSITY'

# PRICING
AI_SUBSCRIPTION_PRICE = 50.00
