from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch, mm
from django.utils import timezone
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import Paragraph, Table, TableStyle

def generate_admit_card_pdf(student, exam_name, exam_date, center):
    """
    Generate Advanced Premium Admit Card
    """
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    
    # --- DESIGN ---
    # Header Background
    c.setFillColor(colors.HexColor("#0f172a")) # Dark Blue
    c.rect(0, height - 120, width, 120, fill=1, stroke=0)
    
    # Logo / Brand
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(width / 2, height - 50, "Y.S.M ADVANCE EDUCATION")
    c.setFont("Helvetica", 14)
    c.drawCentredString(width / 2, height - 75, "OFFICIAL ADMIT CARD")
    
    # Exam Details Box
    c.setStrokeColor(colors.HexColor("#3b82f6"))
    c.setLineWidth(2)
    c.rect(50, height - 250, width - 100, 100, stroke=1, fill=0)
    
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(70, height - 180, f"EXAM: {exam_name.upper()}")
    
    c.setFont("Helvetica", 12)
    c.drawString(70, height - 210, f"Date: {exam_date}")
    c.drawString(300, height - 210, f"Center: {center}")
    
    # Student Details
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 280, "CANDIDATE DETAILS")
    c.line(50, height - 285, 200, height - 285)
    
    c.setFont("Helvetica", 12)
    y = height - 320
    c.drawString(50, y, f"Name: {student.name}")
    c.drawString(50, y - 25, f"Roll No: {student.roll_number}")
    c.drawString(50, y - 50, f"Grade/Class: {student.grade}")
    
    # Instructions
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y - 100, "IMPORTANT INSTRUCTIONS")
    c.line(50, y - 105, 250, y - 105)
    
    instructions = [
        "1. Bring this Admit Card to the examination hall.",
        "2. Do not carry mobile phones or electronic gadgets.",
        "3. Reach the center 30 minutes before the exam time.",
        "4. Use only Blue/Black ball point pen."
    ]
    
    c.setFont("Helvetica", 10)
    inst_y = y - 130
    for inst in instructions:
        c.drawString(50, inst_y, inst)
        inst_y -= 20
        
    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawCentredString(width/2, 30, "Generated by Y.S.M Advance Education System")
    
    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer

def generate_report_card_pdf(student, exam_results):
    """
    Generate Premium Report Card with Tables
    """
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    
    # --- HEADER ---
    c.setFillColor(colors.HexColor("#0f172a"))
    c.rect(0, height - 100, width, 100, fill=1, stroke=0)
    
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 22)
    c.drawCentredString(width / 2, height - 40, "STUDENT PROGRESS REPORT")
    c.setFont("Helvetica", 12)
    c.drawCentredString(width / 2, height - 65, "Academic Year 2024-2025")
    
    # --- STUDENT INFO ---
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, height - 140, f"Student Name: {student.name}")
    c.drawString(350, height - 140, f"Roll No: {student.roll_number}")
    c.drawString(50, height - 160, f"Class: {student.grade}")
    c.drawString(350, height - 160, f"Date: {timezone.now().date()}")
    
    # --- TABLE DATA ---
    data = [['Subject', 'Max Marks', 'Obtained', 'Grade']]
    total_max = 0
    total_obt = 0
    
    for result in exam_results:
        grade = "A" # Logic to calc grade
        percentage = (result['marks'] / result['total']) * 100
        if percentage < 40: grade = "F"
        elif percentage < 60: grade = "C"
        elif percentage < 80: grade = "B"
        
        data.append([
            result['subject'],
            str(result['total']),
            str(result['marks']),
            grade
        ])
        total_max += result['total']
        total_obt += result['marks']
        
    # Total Row
    data.append(['TOTAL', str(total_max), str(total_obt), '-'])
    
    # Draw Table
    table = Table(data, colWidths=[200, 80, 80, 80])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#3b82f6")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'), # Bold Total Row
    ]))
    
    table.wrapOn(c, width, height)
    table.drawOn(c, 50, height - 350)
    
    # --- REMARKS & SIGNATURE ---
    y_pos = height - 450
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y_pos, "Remarks:")
    c.setFont("Helvetica", 10)
    c.drawString(120, y_pos, "Excellent performance! Keep it up.")
    
    c.line(50, y_pos - 100, 200, y_pos - 100)
    c.drawString(70, y_pos - 115, "Class Teacher")
    
    c.line(350, y_pos - 100, 500, y_pos - 100)
    c.drawString(380, y_pos - 115, "Principal")
    
    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer
