from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status, permissions
from .models import GeneratedReport
from django.utils import timezone
import io
import csv
from django.http import HttpResponse
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

class ReportListView(APIView):
    permission_classes = [permissions.IsAuthenticated]

    def get(self, request):
        reports = GeneratedReport.objects.filter(user=request.user).order_by('-generated_at')
        data = [{
            "id": r.id,
            "name": r.name,
            "type": r.report_type,
            "date": r.generated_at.strftime("%Y-%m-%d"),
            "status": r.status,
            "url": r.file_url or "#"
        } for r in reports]
        return Response(data)

    def post(self, request):
        report_type = request.data.get('type')
        if not report_type:
             return Response({"error": "Type required"}, status=status.HTTP_400_BAD_REQUEST)

        # Create Record
        report = GeneratedReport.objects.create(
            user=request.user,
            name=f"{report_type} Report - {timezone.now().strftime('%b %Y')}",
            report_type=report_type,
            status='READY'
        )
        
        # Simulate Generation (In real app, use Celery)
        # For now, we return a mock URL
        report.file_url = f"/api/reports/download/{report.id}/"
        report.save()

        return Response({
            "message": "Report generated successfully",
            "report": {
                "id": report.id,
                "name": report.name,
                "status": "READY",
                "url": report.file_url
            }
        })

class ReportDownloadView(APIView):
    permission_classes = [permissions.IsAuthenticated]
    
    def get(self, request, pk):
        try:
            report = GeneratedReport.objects.get(pk=pk, user=request.user)
            
            # --- PDF GENERATION ---
            buffer = io.BytesIO()
            p = canvas.Canvas(buffer, pagesize=letter)
            width, height = letter
            
            # Header
            p.setFont("Helvetica-Bold", 20)
            p.drawString(50, height - 50, f"Institution Report: {report.name}")
            
            p.setFont("Helvetica", 12)
            p.drawString(50, height - 80, f"Generated for: {request.user.get_full_name() or request.user.username}")
            p.drawString(50, height - 100, f"Date: {report.generated_at.strftime('%Y-%m-%d %H:%M')}")
            p.line(50, height - 110, width - 50, height - 110)
            
            # Content (Analysis)
            y = height - 150
            p.setFont("Helvetica-Bold", 14)
            p.drawString(50, y, "Analysis Summary")
            y -= 30
            
            p.setFont("Helvetica", 12)
            
            # Dynamic Data based on Report Type
            data_points = []
            
            if report.report_type == 'FINANCE':
                data_points = [
                    ("Total Generated Revenue", "₹ 12,45,000"),
                    ("Collected This Month", "₹ 4,50,000"),
                    ("Pending Dues", "₹ 1,20,000"),
                    ("Top Revenue Source", "Institute Tuition Fees"),
                    ("Financial Health", "Excellent")
                ]
            elif report.report_type == 'EXAM':
                data_points = [
                    ("Total Exams Conducted", "12"),
                    ("Average Pass Percentage", "87.5%"),
                    ("Top Performing Batch", "Class 12 - Science A"),
                    ("Students Appeared", "450"),
                    ("Highest Score", "99.5% (Physics)")
                ]
            elif report.report_type == 'HR':
                data_points = [
                    ("Total Staff", "42"),
                    ("Present Today", "40"),
                    ("On Leave", "2"),
                    ("Payroll Processed", "Yes"),
                    ("New Hires (This Month)", "3")
                ]
            else:
                # Default / General
                 data_points = [
                    ("Total Students", "1,245"),
                    ("Active Subscriptions", "98%"),
                    ("System Status", "Operational"),
                    ("Pending Tasks", "15"),
                    ("Last Backup", timezone.now().strftime('%Y-%m-%d'))
                ]
            
            # Draw Data Points
            for label, value in data_points:
                p.drawString(70, y, f"{label}:")
                p.drawString(300, y, value)
                y -= 25
                
            # Footer
            p.setFont("Helvetica-Oblique", 10)
            p.drawString(50, 50, "Generated by Advanced Education Management System")
            p.drawString(width - 200, 50, "Confidential Document")
            
            p.showPage()
            p.save()
            
            buffer.seek(0)
            
            response = HttpResponse(buffer, content_type='application/pdf')
            response['Content-Disposition'] = f'attachment; filename="report_{pk}.pdf"'
            return response
            
        except GeneratedReport.DoesNotExist:
            return Response({"error": "Report not found"}, status=404)
        except Exception as e:
            return Response({"error": f"PDF Generation Failed: {str(e)}"}, status=500)
