from student.views import (
    StudentListCreateView,
    StudentDetailsView,
    StudentTodayView,
    AttendenceCreateView,
    AttendenceDetailsView,
    ProfileView,
    StudentDashboardView,
    TeacherDashboardView,
    ParentDashboardView,
    PaymentListCreateView,
    PaymentDetailsView,
    NotificationListView,
    NotificationMarkReadView,
    NotificationCreateView,
    LandingPageView,
    LoginPageView,
    AdminDashboardTemplateView,
    TeacherDashboardTemplateView,
    StudentDashboardTemplateView,
    ParentDashboardTemplateView,
    DemoRequestView,
    DeveloperProfileView,
    ResumeView,
    ClientSubscriptionView, SubscriptionRenewalView,
    LibraryBookListCreateView, LibraryBookDetailView, BookIssueListCreateView,
    HostelListCreateView, RoomListCreateView, HostelAllocationListCreateView,
    VehicleListCreateView, RouteListCreateView, TransportAllocationListCreateView,
    EmployeeListCreateView, LeaveRequestListCreateView,
    ExamListCreateView, EventListCreateView,
    CourseListCreateView, CourseDetailView, BatchListCreateView, EnrollmentListCreateView, InvoiceDownloadView,
    LiveClassListCreateView, DepartmentListCreateView,
    TeamManagementView, ClientAuditLogListView, DashboardStatsView,
    GenerateIDCardView, GenerateAdmitCardView, GenerateReportCardView
)
from .onboarding_views import OnboardingPaymentView, OnboardingBulkImportView

