from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as PlatypusImage
from reportlab.lib.units import inch, cm
from reportlab.lib.enums import TA_RIGHT, TA_CENTER, TA_LEFT
from reportlab.pdfgen import canvas
from django.utils import timezone
from math import radians, cos, sin, asin, sqrt

# --- SAAS ISOLATION HELPERS ---

def get_owner_user(user):
    """
    Get the owner user for data filtering (multi-tenancy isolation).
    Centralized in utils.py to prevent circular imports between models and views.
    """
    if not user or not user.is_authenticated:
        return None
        
    if user.is_superuser:
        return user
    
    # 1. Check Student Profile
    if hasattr(user, 'student_profile'):
        return user.student_profile.created_by
        
    # 2. Check Employee Profile (Teacher/Staff)
    if hasattr(user, 'employee_profile'):
        return user.employee_profile.created_by
        
    # 3. Check Parent Role
    try:
        if hasattr(user, 'profile') and user.profile.role == 'PARENT':
            from student.models import Student
            child = Student.objects.filter(parent=user).first()
            if child:
                return child.created_by
    except:
        pass

    # 4. If current user is the Client/Admin (Owner)
    try:
        from django.core.exceptions import ObjectDoesNotExist
        profile = user.profile
        if profile.role in ['CLIENT', 'ADMIN']:
            return user
    except ObjectDoesNotExist:
        pass
        
    return user

def filter_by_owner(qs, user, created_by_field='created_by'):
    """
    Filter queryset to show only data owned by the current institution owner.
    SuperUser bypass: Returns unfiltered queryset for full system access.
    """
    # GOD MODE: SuperUser sees everything
    if user.is_superuser:
        return qs
    
    owner = get_owner_user(user)
    if owner:
        return qs.filter(**{created_by_field: owner})
    return qs.none()

# --- GEOMETRIC UTILITIES ---

def haversine(lon1, lat1, lon2, lat2):
    """
    Calculate the great circle distance between two points 
    on the earth (specified in decimal degrees)
    """
    # Convert decimal degrees to radians 
    lon1, lat1, lon2, lat2 = map(radians, [float(lon1), float(lat1), float(lon2), float(lat2)])

    # Haversine formula 
    dlon = lon2 - lon1 
    dlat = lat2 - lat1 
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a)) 
    r = 6371 # Radius of earth in kilometers. Use 3956 for miles
    return c * r * 1000 # Return meters

def validate_coordinates(lat, lon):
    """
    Validate latitude (-90 to 90) and longitude (-180 to 180)
    """
    try:
        lat_f = float(lat)
        lon_f = float(lon)
        if not (-90 <= lat_f <= 90 and -180 <= lon_f <= 180):
            return False
        return True
    except (ValueError, TypeError):
        return False

def draw_header_footer(canvas, doc, profile=None):
    canvas.saveState()
    
    # --- HEADER BACKGROUND ---
    # Premium Blue Header Strip
    canvas.setFillColor(colors.HexColor("#1a237e")) # Deep Royal Blue
    canvas.rect(0, 10.5*inch, 8.5*inch, 1.5*inch, fill=1, stroke=0)
    
    # --- LOGO & BRANDING ---
    inst_name = "Y.S.M"
    inst_sub = "ADVANCE EDUCATION SYSTEM"
    logo_path = None
    
    if profile:
        inst_name = profile.institution_name or "Y.S.M"
        inst_sub = f"{profile.institution_type} MANAGEMENT SYSTEM"
        if profile.institution_logo and hasattr(profile.institution_logo, 'path'):
            import os
            if os.path.exists(profile.institution_logo.path):
                logo_path = profile.institution_logo.path

    canvas.setFillColor(colors.white)
    
    # Draw Logo
    text_x = 0.5*inch
    if logo_path:
        try:
            canvas.drawImage(logo_path, 0.5*inch, 10.7*inch, width=0.7*inch, height=0.7*inch, mask='auto', preserveAspectRatio=True)
            text_x = 1.4*inch
        except: pass

    canvas.setFont("Helvetica-Bold", 22)
    canvas.drawString(text_x, 11*inch, inst_name.upper())
    canvas.setFont("Helvetica", 10)
    canvas.drawString(text_x, 10.8*inch, inst_sub)
    
    # --- INVOICE LABEL ---
    canvas.setFont("Helvetica-Bold", 36)
    canvas.setFillColor(colors.HexColor("#ffd700")) # Gold Color
    canvas.drawRightString(7.8*inch, 11*inch, "INVOICE")
    
    # --- FOOTER ---
    # Bottom Blue Strip
    canvas.setFillColor(colors.HexColor("#1a237e"))
    canvas.rect(0, 0, 8.5*inch, 0.8*inch, fill=1, stroke=0)
    
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica", 9)
    footer_text = f"Official Invoice generated by {inst_name}"
    canvas.drawCentredString(4.125*inch, 0.45*inch, footer_text)
    canvas.drawCentredString(4.125*inch, 0.3*inch, "Powered by Y.S.M Education System | support@ysm.education")
    
    canvas.restoreState()

def generate_invoice_pdf(payment):
    """
    Generate Ultra-Premium Professional Invoice PDF
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=40, leftMargin=40, topMargin=120, bottomMargin=60)
    
    # Get Profile for Branding
    user = payment.user
    profile = getattr(user, 'profile', None)
    
    # Wrapper to pass profile to header/footer
    def header_footer_wrapper(canvas, doc):
        draw_header_footer(canvas, doc, profile=profile)
    
    styles = getSampleStyleSheet()
    
    # --- PREMIUM COLORS ---
    ROYAL_BLUE = colors.HexColor("#1a237e")
    GOLD = colors.HexColor("#ffd700")
    LIGHT_GREY = colors.HexColor("#f8f9fa")
    TEXT_GREY = colors.HexColor("#4a5568")
    
    elements = []
    
    # --- INVOICE META DATA (Right Aligned) ---
    inv_date = timezone.now().strftime('%d %b, %Y')
    inv_no = f"INV-{payment.id:06d}"
    
    # --- BILLING DETAILS ---
    # Two Columns: Billed To (Left) & Invoice Details (Right)
    
    # User Details Style
    p_style = ParagraphStyle('Normal', fontSize=10, leading=14, textColor=TEXT_GREY)
    h_style = ParagraphStyle('Heading', fontSize=12, leading=16, textColor=ROYAL_BLUE, fontName='Helvetica-Bold')
    
    billed_to_html = f"""
    <b>BILLED TO:</b><br/>
    <font size="12" color="#1a237e"><b>{user.get_full_name() or user.username}</b></font><br/>
    {profile.institution_name if profile and profile.institution_name else user.username}<br/>
    {profile.address if profile and profile.address else 'N/A'}<br/>
    {user.email}<br/>
    {profile.phone if profile else ''}
    """
    
    invoice_data_html = f"""
    <b>PAYMENT DETAILS:</b><br/>
    Invoice No: <b>{inv_no}</b><br/>
    Date: <b>{inv_date}</b><br/>
    Mode: <b>{payment.get_payment_mode_display()}</b><br/>
    Txn ID: {payment.transaction_id or 'N/A'}<br/>
    Status: <font color="green"><b>PAID</b></font>
    """
    
    meta_table_data = [
        [Paragraph(billed_to_html, p_style), Paragraph(invoice_data_html, p_style)]
    ]
    
    t_meta = Table(meta_table_data, colWidths=[4*inch, 3*inch])
    t_meta.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('LEFTPADDING', (0,0), (-1,-1), 0),
        ('RIGHTPADDING', (0,0), (-1,-1), 0),
    ]))
    elements.append(t_meta)
    elements.append(Spacer(1, 0.5*inch))
    
    # --- INVOICE ITEMS TABLE ---
    plan_name = profile.institution_type if profile else 'Standard'
    item_desc = f"<b>{plan_name} Plan Subscription</b><br/><font size=9 color='#666'>Access to premium education management modules (30 Days Validity)</font>"
    
    # Header
    table_data = [
        ["DESCRIPTION", "QTY", "PRICE", "TOTAL"], # Header
        [Paragraph(item_desc, p_style), "1", f"Rs. {payment.amount}", f"Rs. {payment.amount}"], # Item
        ["", "", "", ""], # Spacer
        ["", "", "Grand Total:", f"Rs. {payment.amount}"], # Total
    ]
    
    col_widths = [4*inch, 0.8*inch, 1.2*inch, 1.2*inch]
    t_items = Table(table_data, colWidths=col_widths)
    
    # Premium Table Style
    t_items.setStyle(TableStyle([
        # Header Styling
        ('BACKGROUND', (0,0), (-1,0), ROYAL_BLUE),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 10),
        ('BOTTOMPADDING', (0,0), (-1,0), 12),
        ('TOPPADDING', (0,0), (-1,0), 12),
        ('ALIGN', (1,0), (-1,-1), 'RIGHT'), # Numbers Right Aligned
        ('ALIGN', (0,0), (0,-1), 'LEFT'),   # Desc Left Aligned
        
        # Item Row Styling
        ('BACKGROUND', (0,1), (-1,1), colors.white),
        ('TEXTCOLOR', (0,1), (-1,1), TEXT_GREY),
        ('FONTNAME', (0,1), (-1,1), 'Helvetica'),
        ('FONTSIZE', (0,1), (-1,1), 10),
        ('BOTTOMPADDING', (0,1), (-1,1), 15),
        ('TOPPADDING', (0,1), (-1,1), 15),
        ('LINEBELOW', (0,1), (-1,1), 1, colors.HexColor("#e2e8f0")), # Light border
        
        # Total Row Styling
        ('LINEABOVE', (0,-1), (-1,-1), 2, ROYAL_BLUE),
        ('FONTNAME', (2,-1), (-1,-1), 'Helvetica-Bold'),
        ('FONTSIZE', (2,-1), (-1,-1), 14),
        ('TEXTCOLOR', (2,-1), (-1,-1), ROYAL_BLUE),
        ('TOPPADDING', (0,-1), (-1,-1), 15),
    ]))
    
    elements.append(t_items)
    elements.append(Spacer(1, 0.5*inch))

    # --- DIGITAL SIGNATURE SECTION ---
    from reportlab.lib.enums import TA_RIGHT
    if profile and profile.digital_signature and hasattr(profile.digital_signature, 'path'):
        import os
        if os.path.exists(profile.digital_signature.path):
            sig_html = f"<b>Authorized Signatory</b><br/><img src='{profile.digital_signature.path}' width='100' height='40'/><br/>{profile.institution_name or 'Institution Head'}"
            t_sig = Table([[Spacer(1, 1), Paragraph(sig_html, ParagraphStyle('Sig', alignment=TA_RIGHT, fontSize=10))]], colWidths=[4*inch, 3*inch])
            t_sig.setStyle(TableStyle([('ALIGN', (1,0), (1,0), 'RIGHT')]))
            elements.append(t_sig)

    elements.append(Spacer(1, 0.3*inch))
    
    # --- TERMS & CONDITIONS (Boxed) ---
    terms_html = """
    <b>TERMS AND CONDITIONS:</b><br/>
    1. This invoice is officially validated with a digital signature.<br/>
    2. Payment once made is non-refundable.<br/>
    3. Services are valid for 30 days from the date of activation.<br/>
    4. For any billing queries, please contact our support team.
    """
    
    t_terms = Table([[Paragraph(terms_html, ParagraphStyle('Terms', fontSize=8, leading=12, textColor=TEXT_GREY))]], colWidths=[7.2*inch])
    t_terms.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), LIGHT_GREY),
        ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e0")),
        ('LEFTPADDING', (0,0), (-1,-1), 10),
        ('RIGHTPADDING', (0,0), (-1,-1), 10),
        ('TOPPADDING', (0,0), (-1,-1), 10),
        ('BOTTOMPADDING', (0,0), (-1,-1), 10),
    ]))
    elements.append(t_terms)
    
    # --- BUILD ---
    doc.build(elements, onFirstPage=header_footer_wrapper, onLaterPages=header_footer_wrapper)
    buffer.seek(0)
    return buffer
