from .base import *
from student.models import GeneratedReport, Student, Employee, Payment, InstitutionExpense, Grade, AuditLog
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from io import BytesIO
from django.core.files.base import ContentFile
from django.http import HttpResponse

def generate_analytics_pdf(owner, stats, report_type='ANALYTICS_SUMMARY'):
    """
    Generate Admin Analytics Report (Financials + Academic Risk)
    """
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    
    # THEME
    PRIMARY = colors.HexColor("#0f172a") 
    ACCENT = colors.HexColor("#3b82f6")
    
    # Header
    c.setFillColor(PRIMARY)
    c.rect(0, height - 100, width, 100, fill=1, stroke=0)
    
    inst_name = "INSTITUTION ANALYTICS"
    if hasattr(owner, 'profile') and owner.profile.institution_name:
        inst_name = owner.profile.institution_name.upper()
        
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(width/2, height - 50, inst_name)
    c.setFont("Helvetica", 12)
    
    title_map = {
        'FINANCE': 'Financial Statement',
        'ACADEMIC': 'Academic Performance Report',
        'HR': 'HR & Staff Report',
        'ATTENDANCE': 'Attendance Summary',
        'ANALYTICS_SUMMARY': 'Executive Summary'
    }
    report_title = title_map.get(report_type, 'General Report')
    
    c.drawCentredString(width/2, height - 70, f"{report_title} - {timezone.now().date()}")
    
    # Content
    y = height - 150
    x = 50
    
    c.setFillColor(colors.black)
    
    # Helper to check if section should be included
    def show_section(section_type):
        if report_type == 'ANALYTICS_SUMMARY': return True
        return report_type == section_type
    
    # Financials
    if show_section('FINANCE'):
        c.setFont("Helvetica-Bold", 16)
        c.drawString(x, y, "1. Financial Overview")
        y -= 30
        
        financials = stats.get('financials', {})
        c.setFont("Helvetica", 12)
        c.drawString(x+20, y, f"Total Revenue:  Rs. {financials.get('total_revenue', 0):,.2f}")
        y -= 20
        c.drawString(x+20, y, f"Total Expenses: Rs. {financials.get('total_expenses', 0):,.2f}")
        y -= 20
        
        profit = financials.get('net_profit', 0)
        color = colors.green if profit >= 0 else colors.red
        c.setFillColor(color)
        c.setFont("Helvetica-Bold", 12)
        c.drawString(x+20, y, f"Net Profit:     Rs. {profit:,.2f}")
        y -= 40
    
    # Academic Health
    if show_section('ACADEMIC'):
        c.setFillColor(colors.black)
        c.setFont("Helvetica-Bold", 16)
        c.drawString(x, y, "2. Academic Health")
        y -= 30
        
        academic = stats.get('academic_health', {})
        c.setFont("Helvetica", 12)
        c.drawString(x+20, y, f"Success Ratio: {academic.get('success_ratio', 0)}%")
        y -= 20
        c.drawString(x+20, y, f"Students At Risk: {academic.get('at_risk_count', 0)}")
        y -= 40
    
    # Operations
    if show_section('HR') or show_section('ATTENDANCE') or report_type == 'ANALYTICS_SUMMARY':
        c.setFont("Helvetica-Bold", 16)
        c.drawString(x, y, "3. Operational Status")
        y -= 30
        
        c.setFont("Helvetica", 12)
        c.drawString(x+20, y, f"Total Students: {stats.get('students_count', 0)}")
        y -= 20
        c.drawString(x+20, y, f"Active Staff: {stats.get('teachers_count', 0)}")
        y -= 20
        c.drawString(x+20, y, f"Inventory Alerts: {stats.get('inventory_alerts', 0)}")
    
    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.setFillColor(colors.grey)
    c.drawCentredString(width/2, 50, "Generated by Y.S.M Advance ERP System")
    
    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer

class ReportListView(APIView):
    permission_classes = [IsAuthenticated]
    
    def get(self, request):
        owner = get_owner_user(request.user)
        # Assuming GeneratedReport has a 'created_by' field based on my checks
        # But wait, the existing model used 'user' instead of 'created_by' if I recall correctly from line 1223?
        # Let's check model again. 
        # Line 1223: user = models.ForeignKey(User, ...)
        # Line 1215: class GeneratedReport(AuditModel) -> AuditModel usually has created_by
        # If it inherits AuditModel, it has created_by.
        # But it explicitely defines 'user'. I should support 'user' field if it exists.
        
        reports = GeneratedReport.objects.filter(user=request.user).order_by('-generated_at')
        if not reports.exists() and hasattr(request.user, 'created_by'):
             # fallback check
             pass
             
        data = []
        type_map = {
             'ANALYTICS_SUMMARY': 'Executive Summary',
             'FINANCE': 'Financial Report', 
             'ACADEMIC': 'Academic Report',
             'HR': 'HR Report',
             'ATTENDANCE': 'Attendance Report'
        }
        for r in reports:
            data.append({
                "id": r.id,
                "name": r.name,
                "type": r.report_type,
                "type_display": type_map.get(r.report_type, r.report_type.title()),
                "date": r.generated_at.strftime("%Y-%m-%d"),
                "status": r.status
            })
        return Response(data)

    def post(self, request):
        print(f"REPORT REQUEST DATA: {request.data}")
        report_type = request.data.get('report_type') or request.data.get('type')
        owner = get_owner_user(request.user)
        
        # Mappings
        if report_type == 'EXAM': report_type = 'ACADEMIC'
        
        supported_types = ['ANALYTICS_SUMMARY', 'FINANCE', 'ACADEMIC', 'HR', 'ATTENDANCE']
        
        if report_type in supported_types:
            today = timezone.now().date()
            stats = {}

            # --- 1. GATHER DATA BASED ON TYPE ---
            
            # Common Inventory Check
            try:
                from student.models import InventoryItem
                low_stock_count = InventoryItem.objects.filter(created_by=owner, quantity__lte=F('min_stock_level')).count()
            except ImportError:
                low_stock_count = 0

            # FINANCE DATA
            if report_type in ['FINANCE', 'ANALYTICS_SUMMARY']:
                total_revenue = Payment.objects.filter(student__created_by=owner, status='PAID').aggregate(Sum('amount'))['amount__sum'] or 0
                inst_expenses = InstitutionExpense.objects.filter(created_by=owner).aggregate(Sum('amount'))['amount__sum'] or 0
                
                # Add Payroll Expenses
                from student.models import Payroll
                payroll_expenses = Payroll.objects.filter(employee__user__created_by=owner, status='PAID').aggregate(Sum('net_salary'))['net_salary__sum'] or 0
                
                total_expenses = float(inst_expenses) + float(payroll_expenses)
                net_profit = float(total_revenue) - total_expenses
                
                stats['financials'] = {
                    "total_revenue": float(total_revenue),
                    "total_expenses": total_expenses,
                    "net_profit": net_profit,
                    "payroll_total": float(payroll_expenses),
                    "operational_expenses": float(inst_expenses)
                }

            # ACADEMIC DATA
            if report_type in ['ACADEMIC', 'ANALYTICS_SUMMARY']:
                students_count = Student.objects.filter(created_by=owner).count()
                failures_risk_qs = Grade.objects.filter(student__created_by=owner).values('student__id').annotate(avg=Avg('marks_obtained')).filter(avg__lt=40)
                at_risk_count = failures_risk_qs.count()
                success_ratio = 100 - ((at_risk_count / students_count * 100) if students_count > 0 else 0)
                
                stats['academic_health'] = {
                    "at_risk_count": at_risk_count,
                    "success_ratio": round(success_ratio, 2),
                    "total_students": students_count
                }

            # HR DATA
            if report_type in ['HR', 'ANALYTICS_SUMMARY']:
                teachers_count = Employee.objects.filter(created_by=owner).count()
                from student.models import LeaveRequest
                pending_leaves = LeaveRequest.objects.filter(employee__user__created_by=owner, status='PENDING').count()
                
                stats['hr_stats'] = {
                    "total_staff": teachers_count,
                    "pending_leaves": pending_leaves
                }

            # ATTENDANCE DATA
            if report_type in ['ATTENDANCE', 'ANALYTICS_SUMMARY']:
                from student.models import Attendence
                # Today's Student Attendance
                total_students = Student.objects.filter(created_by=owner).count()
                present_students = Attendence.objects.filter(student__created_by=owner, date=today, is_present=True).count()
                absent_students = Attendence.objects.filter(student__created_by=owner, date=today, is_present=False).count()
                
                # If no records for today, maybe show 0 or "Not Marked"
                # Today's Staff Attendance
                total_staff = Employee.objects.filter(created_by=owner).count()
                present_staff = Attendence.objects.filter(employee__user__created_by=owner, date=today, is_present=True).count()
                
                stats['attendance_stats'] = {
                    "date": today.strftime("%Y-%m-%d"),
                    "student_present": present_students,
                    "student_absent": absent_students,
                    "staff_present": present_staff,
                    "total_students": total_students,
                    "total_staff": total_staff,
                    "student_attendance_pct": round((present_students / total_students * 100), 1) if total_students > 0 else 0
                }

            # General Stats (Always include basic counts)
            stats['students_count'] = Student.objects.filter(created_by=owner).count()
            stats['teachers_count'] = Employee.objects.filter(created_by=owner).count()
            stats['inventory_alerts'] = low_stock_count
            
            # 2. Generate PDF
            pdf_buffer = generate_analytics_pdf(owner, stats, report_type)
            
            # 3. Save Report
            filename = f"{report_type.title()}_Report_{timezone.now().date()}.pdf"
            report_name = f"{report_type.replace('_', ' ').title()} Report"
            
            report = GeneratedReport(
                user=request.user,
                created_by=request.user,
                name=report_name,
                report_type=report_type,
                status="COMPLETED"
            )
            
            from django.core.files.storage import default_storage
            from django.core.files.base import ContentFile
            
            path = default_storage.save(f"reports/{filename}", ContentFile(pdf_buffer.getvalue()))
            report.file_url = path 
            report.save()
            
            return Response({
                "message": "Report Generated",
                "report_id": report.id,
                "name": report.name,
                "file_url": report.file_url
            })
            
        return Response({"error": "Invalid Report Type: " + str(report_type)}, status=400)


def generate_analytics_pdf(owner, stats, report_type='ANALYTICS_SUMMARY'):
    """
    Generate Admin Analytics Report (Financials + Academic Risk)
    """
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    
    # THEME
    PRIMARY = colors.HexColor("#0f172a") 
    ACCENT = colors.HexColor("#3b82f6")
    
    # Header
    c.setFillColor(PRIMARY)
    c.rect(0, height - 100, width, 100, fill=1, stroke=0)
    
    inst_name = "INSTITUTION ANALYTICS"
    if hasattr(owner, 'profile') and owner.profile.institution_name:
        inst_name = owner.profile.institution_name.upper()
        
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(width/2, height - 50, inst_name)
    c.setFont("Helvetica", 12)
    
    title_map = {
        'FINANCE': 'Financial Statement',
        'ACADEMIC': 'Academic Performance Report',
        'HR': 'HR & Staff Report',
        'ATTENDANCE': 'Daily Attendance Report',
        'ANALYTICS_SUMMARY': 'Executive Summary'
    }
    report_title = title_map.get(report_type, 'General Report')
    
    c.drawCentredString(width/2, height - 70, f"{report_title} - {timezone.now().date()}")
    
    # Content
    y = height - 150
    x = 50
    
    c.setFillColor(colors.black)
    
    # Helper to check if section should be included
    def show_section(section_type):
        if report_type == 'ANALYTICS_SUMMARY': return True
        return report_type == section_type
    
    # --- FINANCE SECTION ---
    if show_section('FINANCE') and 'financials' in stats:
        c.setFont("Helvetica-Bold", 16)
        c.drawString(x, y, "1. Financial Overview")
        y -= 30
        
        financials = stats.get('financials', {})
        c.setFont("Helvetica", 12)
        c.drawString(x+20, y, f"Total Revenue:  Rs. {financials.get('total_revenue', 0):,.2f}")
        y -= 20
        c.drawString(x+20, y, f"Total Expenses: Rs. {financials.get('total_expenses', 0):,.2f}")
        y -= 20
        c.drawString(x+40, y, f"(Payroll: {financials.get('payroll_total', 0):,.2f}, Ops: {financials.get('operational_expenses', 0):,.2f})")
        y -= 30
        
        profit = financials.get('net_profit', 0)
        color = colors.green if profit >= 0 else colors.red
        c.setFillColor(color)
        c.setFont("Helvetica-Bold", 12)
        c.drawString(x+20, y, f"Net Profit:     Rs. {profit:,.2f}")
        c.setFillColor(colors.black)
        y -= 40
    
    # --- ACADEMIC SECTION ---
    if show_section('ACADEMIC') and 'academic_health' in stats:
        c.setFillColor(colors.black)
        c.setFont("Helvetica-Bold", 16)
        c.drawString(x, y, "2. Academic Health")
        y -= 30
        
        academic = stats.get('academic_health', {})
        c.setFont("Helvetica", 12)
        c.drawString(x+20, y, f"Success Ratio: {academic.get('success_ratio', 0)}%")
        y -= 20
        c.drawString(x+20, y, f"Students At Risk: {academic.get('at_risk_count', 0)}")
        y -= 20
        c.drawString(x+20, y, f"Total Students Evaluated: {academic.get('total_students', 0)}")
        y -= 40

    # --- HR SECTION ---
    if show_section('HR') and 'hr_stats' in stats:
        c.setFillColor(colors.black)
        c.setFont("Helvetica-Bold", 16)
        c.drawString(x, y, "3. HR & Staffing")
        y -= 30
        
        hr = stats.get('hr_stats', {})
        c.setFont("Helvetica", 12)
        c.drawString(x+20, y, f"Total Active Staff: {hr.get('total_staff', 0)}")
        y -= 20
        c.drawString(x+20, y, f"Pending Leave Requests: {hr.get('pending_leaves', 0)}")
        y -= 40
    
    # --- ATTENDANCE SECTION ---
    if show_section('ATTENDANCE') and 'attendance_stats' in stats:
        c.setFillColor(colors.black)
        c.setFont("Helvetica-Bold", 16)
        c.drawString(x, y, "4. Attendance Status")
        y -= 30
        
        att = stats.get('attendance_stats', {})
        c.setFont("Helvetica", 12)
        c.drawString(x+20, y, f"Date: {att.get('date')}")
        y -= 20
        c.drawString(x+20, y, f"Student Attendance: {att.get('student_attendance_pct', 0)}% ({att.get('student_present', 0)}/{att.get('total_students', 0)})")
        y -= 20
        c.drawString(x+20, y, f"Staff Present: {att.get('staff_present', 0)}/{att.get('total_staff', 0)}")
        y -= 40
    
    # Operations Summary (Fallback/Extra)
    if report_type == 'ANALYTICS_SUMMARY':
        c.setFont("Helvetica-Bold", 16)
        c.drawString(x, y, "5. Operational Status")
        y -= 30
        c.setFont("Helvetica", 12)
        c.drawString(x+20, y, f"Inventory Alerts: {stats.get('inventory_alerts', 0)}")
        y -= 30
    
    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.setFillColor(colors.grey)
    c.drawCentredString(width/2, 50, "Generated by Y.S.M Advance ERP System")
    
    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer

class ReportDownloadView(APIView):
    permission_classes = [IsAuthenticated]
    
    def get(self, request, pk):
        report = get_object_or_404(GeneratedReport, pk=pk)
        
        # Verify ownership
        if report.user != request.user and not request.user.is_superuser:
            return Response({"error": "Access Denied"}, status=403)

        # Serve File
        from django.core.files.storage import default_storage
        if default_storage.exists(report.file_url):
             file = default_storage.open(report.file_url, 'rb')
             response = HttpResponse(file, content_type='application/pdf')
             response['Content-Disposition'] = f'attachment; filename="{report.name}.pdf"'
             return response
        else:
             return Response({"error": "File not found"}, status=404)
