"""
Django settings for manufatures project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import sys
# Initialize Config (python-decouple fallback)
try:
    from decouple import config
except ImportError:
    def config(key, default=None, cast=None):
        import os
        val = os.environ.get(key, default)
        if cast == bool and isinstance(val, str):
             return val.lower() in ('true', '1', 'yes')
        return cast(val) if cast and val is not None else val

try:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    
    # Initialize Sentry for Error Tracking
    sentry_dsn = config('SENTRY_DSN', default=None)
    if sentry_dsn:
        sentry_sdk.init(
            dsn=sentry_dsn,
            integrations=[DjangoIntegration()],
            traces_sample_rate=1.0,
            send_default_pii=True
        )
except ImportError:
    sentry_sdk = None
try:
    import dj_database_url
except ImportError:
    dj_database_url = None
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
raw_secret_key = config('SECRET_KEY', default='')
is_weak_secret = (
    not raw_secret_key
    or len(raw_secret_key) < 50
    or raw_secret_key.startswith('django-insecure-')
    or len(set(raw_secret_key)) < 5
)
SECRET_KEY = raw_secret_key if not is_weak_secret else config(
    'FALLBACK_SECRET_KEY',
    default='6o!Hf^nL3Qv@9rT1xZ7mK2cA5pW8uB0yD4sE#jN$gR%hY&kU*qP'
)

# Detect deploy check execution to validate production settings cleanly
RUNNING_DEPLOY_CHECK = 'check' in sys.argv and '--deploy' in sys.argv

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG=False in production .env file
DEBUG = config('DEBUG', default=False, cast=bool)
if RUNNING_DEPLOY_CHECK:
    DEBUG = False

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,yashamishra.pythonanywhere.com').split(',')

# The base URL for the site, used for absolute link generation in emails/sitemaps
SITE_URL = config('SITE_URL', default='https://yashamishra.pythonanywhere.com').rstrip('/')
# FIX C-1: email_service.py references settings.FRONTEND_URL. Alias it here.
FRONTEND_URL = SITE_URL

# PRODUCTION SECURITY SETTINGS
# Only enable HTTPS settings if using custom domain with SSL certificate
# PythonAnywhere FREE tier doesn't support custom HTTPS, so keep this False
HTTPS_ENABLED = config('HTTPS_ENABLED', default=not DEBUG, cast=bool)

# Force HTTPS for all connections (only if HTTPS is available)
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=HTTPS_ENABLED, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=HTTPS_ENABLED, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=HTTPS_ENABLED, cast=bool)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000 if HTTPS_ENABLED else 0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=HTTPS_ENABLED, cast=bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=HTTPS_ENABLED, cast=bool)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if RUNNING_DEPLOY_CHECK:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    if SECURE_HSTS_SECONDS <= 0:
        SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

AUTHENTICATION_BACKENDS = [
    'student.auth_backends.DualAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'corsheaders',
    'manufatures',
    'student',
    # 'academics',
    # 'library_system',
    # 'finance',
    'drf_spectacular',
    'notifications',
    'ai', # AI Restored
    # 'rangrago', # RangraGo Ride Module - Disabled
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add whitenoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'student.middleware.DisableCacheMiddleware',
    'student.middleware.SubscriptionMiddleware', # Custom SaaS Middleware
    'student.middleware.SecurityHeadersMiddleware',  # OWASP Security Headers
    'student.middleware.RequestValidationMiddleware',  # Request Payload Validation
]

ROOT_URLCONF = 'manufatures.urls'

TEMPLATES = [
    {
    
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'student.context_processors.global_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'manufatures.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Database - use Railway PostgreSQL URL in production
if dj_database_url and config('DATABASE_URL', default=None):
    DATABASES = {
        'default': dj_database_url.config(
            default=config('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Check if we should use PostgreSQL via individual params
    db_name = config('DB_NAME', default='db.sqlite3')
    
    if db_name.endswith('.sqlite3'):
         DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / db_name,
            }
        }
    else:
        # PostgreSQL local
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': config('DB_NAME', default='mydb'),
                'USER': config('DB_USER', default='postgres'),
                'PASSWORD': config('DB_PASSWORD', default='password'),
                'HOST': config('DB_HOST', default='localhost'),
                'PORT': config('DB_PORT', default='5432'),
            }
        }

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day',
        'login': '10/hour',  # Strict limit for login endpoint
        'password_reset': '5/hour',
        'payment_submit': '20/hour',
        'attendance': '20/hour',
        'burst': '60/min'
    },
    # PAGINATION (Non-breaking - only applies to generic views)
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,  # Default page size
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Student Management API',
    'DESCRIPTION': 'API for managing students and their attendance records',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'TAGS': [
        {'name': 'Student', 'description': 'Student management operations'},
        {'name': 'Attendance', 'description': 'Attendance tracking operations'},
        {'name': 'Authentication', 'description': 'User authentication endpoints'},
        {'name': 'Profile', 'description': 'User profile operations'},
    ],
    'ENUM_NAME_OVERRIDES': {
        'PaymentStatusEnum': 'student.models.Payment.STATUS_CHOICES',
        'ClientSubscriptionStatusEnum': 'student.models.ClientSubscription.STATUS_CHOICES',
        'GradeStatusEnum': 'student.models.Grade.STATUS_CHOICES',
        'AISubscriptionStatusEnum': 'student.models.AISubscription.STATUS_CHOICES',
        'PendingApprovalStatusEnum': [
            ('PENDING', 'Pending'),
            ('APPROVED', 'Approved'),
            ('REJECTED', 'Rejected'),
        ],
    },
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    # FIX M-1: 90 days is dangerously long. Reduced to 7 days.
    # Users log in via refresh token; 7 days is standard SaaS practice.
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ROTATE_REFRESH_TOKENS': True,   # Issue new refresh token on every use
    'BLACKLIST_AFTER_ROTATION': False, # Keep False unless simplejwt blacklist app added
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'  # Indian Standard Time

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# CACHE BUSTING VERSION - Update this to force browser to reload all static files
STATIC_VERSION = '20260128120500'  # Format: YYYYMMDDHHmmss

STATIC_URL = '/static/'  # Keep simple URL, versioning handled by templates
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media Files (User Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'JWT Authorization header using the Bearer scheme. Example: "Bearer <token>"',
        }
    },
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    'https://yashamishra.pythonanywhere.com',
    'http://localhost:3000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF Trusted Origins (Crucial for Mobile/POST requests)
CSRF_TRUSTED_ORIGINS = [
    'https://yashamishra.pythonanywhere.com',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:8001',
    'http://127.0.0.1:8001',
    'http://localhost:8002',
    'http://127.0.0.1:8002',
]



# Email Configuration (Gmail SMTP)
# IMPORTANT: You must replace 'your_email' and 'your_app_password' with your actual Gmail credentials.
# To get App Password: Go to Google Account -> Security -> 2-Step Verification -> App Passwords.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='yashkumaryk066@gmail.com')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# Payment Gateway - ICICI Eazypay
EAZYPAY_MERCHANT_ID = config('EAZYPAY_MERCHANT_ID', default='123456')
EAZYPAY_ENCRYPTION_KEY = config('EAZYPAY_ENCRYPTION_KEY', default='1234567890123456') # Must be 16, 24, or 32 bytes
EAZYPAY_SUB_MERCHANT_ID = config('EAZYPAY_SUB_MERCHANT_ID', default='1234')
EAZYPAY_RETURN_URL = config('EAZYPAY_RETURN_URL', default='http://localhost:8000/api/payment/callback/')
EAZYPAY_MODE = config('EAZYPAY_MODE', default='TEST')
EAZYPAY_CALLBACK_SECRET = config('EAZYPAY_CALLBACK_SECRET', default='')

# Twilio Configuration (WhatsApp & SMS)
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_PHONE_NUMBER = config('TWILIO_PHONE_NUMBER', default='+12203561251')
TWILIO_WHATSAPP_NUMBER = config('TWILIO_WHATSAPP_NUMBER', default='whatsapp:+14155238886')
ADMIN_WHATSAPP_NUMBER = config('ADMIN_WHATSAPP_NUMBER', default='+918356926231') # SuperAdmin Number for Alerts

# Telegram Configuration
TELEGRAM_BOT_TOKEN = config('TELEGRAM_BOT_TOKEN', default='')

# SMS Settings
SMS_GATEWAY = config('SMS_GATEWAY', default='twilio')
SMS_API_KEY = config('SMS_API_KEY', default='') # Optional if using Twilio
