# Generated by Django 5.2.8 on 2025-12-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendence',
            unique_together={('student', 'date')},
        ),
    ]
