# Generated by Django 6.0 on 2025-12-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_attendence_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='is_persent',
            new_name='is_present',
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
