# Generated by Django 6.0 on 2025-12-30 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_parent_student_user_notification_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, unique=True)),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('LAB', 'Laboratory'), ('AUDITORIUM', 'Auditorium'), ('LIBRARY', 'Library'), ('SPORTS', 'Sports')], default='CLASSROOM', max_length=20)),
                ('capacity', models.IntegerField()),
                ('floor', models.IntegerField(default=1)),
                ('building', models.CharField(blank=True, max_length=50)),
                ('facilities', models.TextField(blank=True, help_text='Projector, AC, Smart Board, etc.')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('credits', models.IntegerField(default=3)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('ACADEMIC', 'Academic'), ('CULTURAL', 'Cultural'), ('SPORTS', 'Sports'), ('TECHNICAL', 'Technical'), ('SOCIAL', 'Social'), ('OTHER', 'Other')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hostel_type', models.CharField(choices=[('BOYS', 'Boys Hostel'), ('GIRLS', 'Girls Hostel'), ('CO-ED', 'Co-Ed Hostel')], max_length=10)),
                ('total_rooms', models.IntegerField()),
                ('address', models.TextField()),
                ('facilities', models.TextField(blank=True, help_text='WiFi, Gym, Mess, etc.')),
                ('warden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hostels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('floor', models.IntegerField()),
                ('capacity', models.IntegerField(default=2, help_text='Number of beds')),
                ('current_occupancy', models.IntegerField(default=0)),
                ('room_type', models.CharField(default='Standard', help_text='Standard, Deluxe, AC, Non-AC', max_length=50)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='student.hostel')),
            ],
            options={
                'ordering': ['hostel', 'floor', 'room_number'],
                'unique_together': {('hostel', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='HostelAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('VACATED', 'Vacated'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=10)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocations', to='student.student')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='student.room')),
            ],
            options={
                'ordering': ['-check_in_date'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_type', models.CharField(choices=[('PARTICIPANT', 'Participant'), ('ORGANIZER', 'Organizer'), ('VOLUNTEER', 'Volunteer')], default='PARTICIPANT', max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='student.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registration_date'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('section', models.CharField(help_text='Class 10-A, BSc-CS-I, etc.', max_length=50)),
                ('academic_year', models.CharField(default='2024-25', max_length=20)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='student.classroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_schedules', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='student.subject')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('classroom', 'day_of_week', 'start_time', 'academic_year')},
            },
        ),
    ]
