# Generated by Django 5.2.9 on 2026-01-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_course_alter_exam_grade_class_alter_exam_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='institution_type',
            field=models.CharField(choices=[('SCHOOL', 'School'), ('COACHING', 'Coaching'), ('INSTITUTE', 'Institute/College')], default='SCHOOL', max_length=20),
        ),
    ]
