# Generated by Django 5.2.9 on 2026-01-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='institution_type',
            field=models.CharField(choices=[('SCHOOL', 'School'), ('COACHING', 'Coaching'), ('INSTITUTE', 'Institute/University')], default='SCHOOL', max_length=20),
        ),
    ]
