# Generated by Django 5.2.9 on 2026-01-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_userprofile_subscription_expiry_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_expiry',
            field=models.DateField(blank=True, null=True),
        ),

    ]
