# Generated by Django 5.2.9 on 2026-01-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_clientsubscription'),
    ]

    operations = [

        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent'), ('ADMIN', 'Admin'), ('CLIENT', 'Client')], max_length=10),
        ),
    ]
