# Generated by Django 5.2.9 on 2026-01-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_userprofile_subscription_expiry_and_more'),
    ]

    operations = [

    ]
