# Generated by Django 5.2.9 on 2026-01-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_userprofile_subscription_expiry'),
    ]

    operations = [

    ]
