# Generated by Django 5.2.9 on 2026-01-03 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_userprofile_subscription_expiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('FINANCE', 'Financial Statement'), ('ACADEMIC', 'Academic Performance'), ('ATTENDANCE', 'Attendance Log'), ('HR', 'HR & Payroll')], max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='READY', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
