# Generated by Django 5.2.9 on 2026-01-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_userprofile_subscription_expiry_generatedreport'),
    ]

    operations = [

    ]
