# Generated by Django 5.2.9 on 2026-01-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_userprofile_subscription_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
