# Generated by Django 5.2.9 on 2026-01-03 17:07

from django.db import migrations, models, connection

def safe_add_column(apps, schema_editor):
    """
    Adds the subscription_expiry column only if it does not check_structure
    to avoid OperationalError: duplicate column name.
    """
    with connection.cursor() as cursor:
        # Check if column exists in SQLite
        cursor.execute("PRAGMA table_info(student_userprofile)")
        columns = [info[1] for info in cursor.fetchall()]
        
        if 'subscription_expiry' not in columns:
            # Column missing, add it using raw SQL since we are bypassing AddField DB op
            cursor.execute("ALTER TABLE student_userprofile ADD COLUMN subscription_expiry date NULL")
        else:
            print("   -> Column 'subscription_expiry' already exists. Skipping creation.")

class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_userprofile_subscription_expiry'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(safe_add_column, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='userprofile',
                    name='subscription_expiry',
                    field=models.DateField(blank=True, null=True),
                ),
            ]
        ),
    ]
