# Generated by Django 5.2.9 on 2026-01-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_payment_payment_type_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsubscription',
            name='plan_type',
            field=models.CharField(choices=[('SCHOOL', 'School Management'), ('COACHING', 'Coaching Management'), ('INSTITUTE', 'Institute Management')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='clientsubscription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='institution_type',
            field=models.CharField(choices=[('SCHOOL', 'School'), ('COACHING', 'Coaching'), ('INSTITUTE', 'Institute/University')], db_index=True, default='SCHOOL', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent'), ('ADMIN', 'Admin'), ('CLIENT', 'Client')], db_index=True, max_length=10),
        ),
    ]
