# Generated by Django 5.2.9 on 2026-01-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_add_plan_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('ONLINE', 'Online (Razorpay/Stripe)'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer (NEFT/IMPS)'), ('UPI', 'UPI (GPay/PhonePe)'), ('CHEQUE', 'Cheque/DD')], default='ONLINE', max_length=20),
        ),
    ]
