# Generated by Django 6.0 on 2026-01-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_add_student_id_card_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Linked Telegram Chat ID', max_length=50, null=True),
        ),
    ]
