# Generated by Django 6.0 on 2026-01-09 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_userprofile_telegram_chat_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIAL', 'Free Trial (7 Days)'), ('EXPIRED', 'Trial Expired'), ('PENDING', 'Payment Pending'), ('ACTIVE', 'Premium Active')], default='TRIAL', max_length=20)),
                ('trial_start_date', models.DateTimeField(auto_now_add=True)),
                ('premium_expiry_date', models.DateField(blank=True, null=True)),
                ('last_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
