# Generated by Django 6.0 on 2026-01-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_aisubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent'), ('ADMIN', 'Admin'), ('CLIENT', 'Client'), ('AI_USER', 'AI User')], db_index=True, max_length=10),
        ),
    ]
