# Generated by Django 5.0.1 on 2026-01-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0036_globalannouncement_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
