# Generated by Django 5.0.1 on 2026-01-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_student_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
