# Generated by Django 5.0.1 on 2026-01-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0038_userprofile_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='digital_signature',
            field=models.ImageField(blank=True, help_text='Upload Administrator Digital Signature', null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institution_logo',
            field=models.ImageField(blank=True, help_text='Upload your School/Institute Logo', null=True, upload_to='institution_logos/'),
        ),
    ]
