# Generated by Django 5.0.1 on 2026-01-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_userprofile_digital_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='attendance_radius',
            field=models.PositiveIntegerField(default=200, help_text='Allowed radius in meters for attendance'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Institution Latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_long',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Institution Longitude', max_digits=9, null=True),
        ),
    ]
