# Generated by Django 5.0.1 on 2026-01-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0040_userprofile_attendance_radius_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent'), ('ADMIN', 'Admin'), ('CLIENT', 'Client'), ('HR', 'HR/Manager'), ('AI_USER', 'AI User')], db_index=True, max_length=10),
        ),
    ]
