# Generated by Django 5.0.1 on 2026-01-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0042_userprofile_force_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarybook',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Book Cover Scan', null=True, upload_to='library_covers/'),
        ),
        migrations.AddField(
            model_name='librarybook',
            name='description',
            field=models.TextField(blank=True, help_text='Synopsis or details'),
        ),
    ]
