# Generated by Django 5.0.1 on 2026-01-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0047_userprofile_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='temp_password',
            field=models.CharField(blank=True, help_text='Temporary password for initial setup visibility', max_length=128, null=True),
        ),
    ]
