# Generated by Django 5.0.1 on 2026-01-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0048_userprofile_temp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, help_text='Unique admission ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parents_phone',
            field=models.CharField(blank=True, help_text='Parent contact number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.CharField(blank=True, help_text='Class/Grade/Section', max_length=50, null=True),
        ),
    ]
