# Generated by Django 5.0.1 on 2026-01-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0050_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_category',
            field=models.CharField(blank=True, choices=[('TUITION', 'Tuition/Course Fee'), ('REGISTRATION', 'Registration/Admission Fee'), ('EXAM', 'Exam/Test Series Fee'), ('TRANSPORT', 'Transport/Bus Fee'), ('HOSTEL', 'Hostel/Mess Fee'), ('LIBRARY', 'Library Fine/Fee'), ('LAB', 'Laboratory Fee'), ('MATERIAL', 'Study Material Fee'), ('LATE_FINE', 'Late Payment Fine'), ('OTHER', 'Other/Miscellaneous')], default='TUITION', max_length=20, null=True),
        ),
    ]
