# Generated by Django 5.0.1 on 2026-01-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0051_payment_payment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_category',
            field=models.CharField(blank=True, choices=[('TUITION', 'Tuition/Monthly Fee'), ('ADMISSION', 'Admission/Registration Fee'), ('ANNUAL', 'Annual/Development Fee'), ('EXAM', 'Exam/Assessment Fee'), ('TRANSPORT', 'Transport/Bus Fee'), ('HOSTEL', 'Hostel/Lodging Fee'), ('MESS', 'Mess/Food Fee'), ('LIBRARY', 'Library Fee/Fine'), ('LAB', 'Laboratory/Practical Fee'), ('COMPUTER', 'Computer/IT Fee'), ('MATERIAL', 'Books/Study Material'), ('UNIFORM', 'Uniform/Accessories'), ('EVENT', 'Event/Picnic/Function'), ('SECURITY', 'Security Deposit (Refundable)'), ('PROSPECTUS', 'Prospectus/Form Fee'), ('LATE_FINE', 'Late Payment Fine'), ('OTHER', 'Other/Miscellaneous')], default='TUITION', max_length=20, null=True),
        ),
    ]
