# Generated by Django 5.0.1 on 2026-01-30 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0054_assignmentsubmission_institutionexpense_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('source', models.CharField(choices=[('WALK_IN', 'Walk-in'), ('REFERRAL', 'Referral'), ('SOCIAL_MEDIA', 'Facebook/Insta'), ('WEBSITE', 'Website'), ('OTHER', 'Other')], default='WALK_IN', max_length=50)),
                ('status', models.CharField(choices=[('NEW', 'New Enquiry'), ('CONTACTED', 'Contacted'), ('DEMO_SCHEDULED', 'Demo Scheduled'), ('DEMO_DONE', 'Demo Attended'), ('INTERESTED', 'Interested'), ('NEGOTIATION', 'Negotiation/Discount'), ('CONVERTED', 'Admitted'), ('LOST', 'Lost')], default='NEW', max_length=20)),
                ('probability_score', models.IntegerField(default=0, help_text='AI Predicted Conversion Chance (0-100)')),
                ('follow_up_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('course_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.course')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubstituteAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('period_slot', models.CharField(help_text='e.g., 2nd Period (10:00-11:00)', max_length=50)),
                ('grade_class', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('is_notified', models.BooleanField(default=False)),
                ('absent_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='student.employee')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='student.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
