# Generated by Django 5.0.1 on 2026-02-02 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0055_studentlead_substituteallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.department'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='grade',
            field=models.CharField(blank=True, help_text='For Schools (e.g. 10)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='section',
            field=models.CharField(blank=True, help_text='For Schools (e.g. A)', max_length=50, null=True),
        ),
    ]
