# Generated by Django 5.0.1 on 2026-02-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0056_liveclass_department_liveclass_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='student@telepathyinfotech.com', help_text='Mandatory student or parent email for official communication', max_length=255),
            preserve_default=False,
        ),
    ]
