# Generated by Django 5.0.1 on 2026-02-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0057_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, help_text='Optional parent-specific email for separate notifications', max_length=255, null=True),
        ),
    ]
