# Generated by Django 5.0.1 on 2026-02-03 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0058_student_parent_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentleaverequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='studentleaverequest',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentleaverequest',
            name='applied_by',
            field=models.ForeignKey(default=1, help_text='User who submitted (Parent/Student)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentleaverequest',
            name='leave_type',
            field=models.CharField(choices=[('SICK', 'Sick Leave'), ('CASUAL', 'Casual / Personal'), ('EMERGENCY', 'Family Emergency'), ('OTHER', 'Other')], default='CASUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='studentleaverequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_student_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentleaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='student_leaves/'),
        ),
        migrations.AlterField(
            model_name='studentleaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15),
        ),
    ]
