# Generated by Django 5.0.1 on 2026-02-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0059_alter_studentleaverequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='attendance_radius',
            field=models.PositiveIntegerField(default=100, help_text='Allowed radius in meters for attendance'),
        ),
    ]
