# Generated by Django 5.2.9 on 2026-02-04 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0060_lmsassignment_grade_class_alter_subject_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsassignment',
            name='grade_class',
            field=models.CharField(blank=True, help_text='Target Class/Grade', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('roll_number', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('code', 'created_by')},
        ),
    ]
