# Generated by Django 5.0.1 on 2026-02-06 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0061_lmsassignment_grade_class_alter_subject_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('grade_class', models.CharField(blank=True, help_text='For School/Institute classes', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('start_window', models.DateTimeField(help_text='When students can start the exam')),
                ('end_window', models.DateTimeField(help_text='Deadline to complete the exam')),
                ('duration_minutes', models.IntegerField(default=60)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('manual_pdf', models.FileField(blank=True, help_text='Optional manual question paper', null=True, upload_to='exam_papers/')),
                ('lockdown_mode', models.BooleanField(default=True, help_text='Enforce fullscreen and tab-lock')),
                ('allow_navigation', models.BooleanField(default=False, help_text='If False, auto-submits on tab switch')),
                ('max_violations', models.IntegerField(default=3, help_text='Number of tab-switches allowed before auto-submit')),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('passing_percentage', models.IntegerField(default=33)),
                ('is_published', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_exams', to='student.batch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_exams', to='student.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('violation_count', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.TextField(blank=True)),
                ('score_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_submitted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Talking Exam'), ('SUBMITTED', 'Submitted'), ('TERMINATED', 'Terminated (Proctoring Violation)'), ('GRADED', 'Graded')], default='IN_PROGRESS', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='student.student')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='student.onlineexam')),
            ],
            options={
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='OnlineQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('TF', 'True / False'), ('SA', 'Short Answer')], default='MCQ', max_length=10)),
                ('options', models.JSONField(blank=True, default=dict, null=True)),
                ('correct_answer', models.CharField(help_text='For MCQ: Key (A/B/C), For TF: True/False', max_length=255)),
                ('marks', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('explanation', models.TextField(blank=True, help_text='AI or Teacher explanation for the correct answer')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='student.onlineexam')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('marked_answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='student.examattempt')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.onlinequestion')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
