# Generated by Django 5.0.1 on 2026-02-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0062_onlineexam_examattempt_onlinequestion_examresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineexam',
            name='is_ai_generated',
        ),
        migrations.RemoveField(
            model_name='onlineexam',
            name='manual_pdf',
        ),
        migrations.AddField(
            model_name='onlineexam',
            name='knowledge_base_file',
            field=models.FileField(blank=True, help_text='Upload a book or reference for AI to generate questions', null=True, upload_to='exam_kb/'),
        ),
        migrations.AddField(
            model_name='onlineexam',
            name='num_long',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='onlineexam',
            name='num_mcq',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='onlineexam',
            name='num_short',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='onlineexam',
            name='require_geofencing',
            field=models.BooleanField(default=False, help_text='Exam can only start within premises'),
        ),
        migrations.AlterField(
            model_name='onlinequestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('TF', 'True / False'), ('SA', 'Short Answer'), ('LA', 'Long Answer')], default='MCQ', max_length=10),
        ),
    ]
