# Generated by Django 5.0.1 on 2026-02-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0063_remove_onlineexam_is_ai_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='is_ai_graded',
            field=models.BooleanField(default=False, help_text='Set to True when AI evaluation is complete'),
        ),
        migrations.AddField(
            model_name='examresponse',
            name='ai_accuracy_score',
            field=models.IntegerField(default=0, help_text='AI calculated accuracy (0-100)'),
        ),
        migrations.AddField(
            model_name='examresponse',
            name='ai_feedback',
            field=models.TextField(blank=True, help_text='Constructive feedback from Sovereign AI'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'Taking Exam'), ('SUBMITTED', 'Submitted'), ('TERMINATED', 'Terminated (Proctoring Violation)'), ('GRADED', 'Graded')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='examresponse',
            name='marked_answer',
            field=models.TextField(),
        ),
    ]
