# Generated by Django 5.0.1 on 2026-02-06 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0064_examattempt_is_ai_graded_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='plagiarism_score',
            field=models.IntegerField(default=0, help_text='AI detected probability of external content (0-100)'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='is_ai_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StudentPerformanceInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('subject_mastery', models.JSONField(default=dict)),
                ('weak_topics', models.JSONField(default=list)),
                ('strong_topics', models.JSONField(default=list)),
                ('ai_recommendation', models.TextField(blank=True)),
                ('learning_path', models.JSONField(default=list, help_text='Multi-step roadmap generated by AI')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='student.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
