# Generated by Django 5.0.1 on 2026-02-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0066_examattempt_result_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineexam',
            name='admit_cards_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onlineexam',
            name='assigned_batches',
            field=models.ManyToManyField(blank=True, help_text='Assign this exam to specific batches', to='student.batch'),
        ),
        migrations.AddField(
            model_name='onlineexam',
            name='roll_code',
            field=models.CharField(default='YSM-2026', help_text='Unique Center/Exam Code for Admit Card Verification', max_length=20),
        ),
    ]
