# Generated by Django 5.0.1 on 2026-02-06 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0067_onlineexam_admit_cards_sent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['institution_type', 'grade'], name='student_stu_institu_5ef951_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['roll_number', 'institution_type'], name='student_stu_roll_nu_6c9b1b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['email'], name='student_stu_email_3e40fe_idx'),
        ),
    ]
