# Generated by Django 5.0.1 on 2026-02-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0068_student_student_stu_institu_5ef951_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
