# Generated by Django 5.0.1 on 2026-02-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0072_resumedownload_notification_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='report_type',
            field=models.CharField(choices=[('FINANCE', 'Financial Statement'), ('ACADEMIC', 'Academic Performance'), ('ATTENDANCE', 'Attendance Log'), ('HR', 'HR & Payroll'), ('ANALYTICS_SUMMARY', 'Analytics Summary')], max_length=50),
        ),
    ]
