# Generated by Django 5.0.1 on 2026-02-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0073_alter_generatedreport_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='institution_type',
            field=models.CharField(choices=[('SCHOOL', 'School'), ('COACHING', 'Coaching'), ('INSTITUTE', 'Institute/University'), ('EDUCATION SYSTEM', 'Education System')], db_index=True, default='COACHING', max_length=20),
        ),
    ]
