# Generated by Django 5.0.1 on 2026-02-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0074_alter_userprofile_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_activity_date',
            field=models.DateField(blank=True, help_text='Date of last significant activity', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak_count',
            field=models.IntegerField(default=0, help_text='Consecutive days of activity'),
        ),
    ]
