# Generated by Django 6.0 on 2026-01-12 07:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('current_lat', models.FloatField(default=0.0)),
                ('current_lng', models.FloatField(default=0.0)),
                ('vehicle_type', models.CharField(choices=[('BIKE', 'Rangra Bike 🏍️'), ('AUTO', 'Rangra Auto 🛺'), ('MINI', 'Rangra Mini 🚗'), ('SEDAN', 'Rangra Prime 🚘'), ('SUV', 'Rangra SUV 🚙')], default='BIKE', max_length=10)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('license_number', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=5.0)),
                ('total_rides', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rangrago_driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_location', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('drop_lat', models.FloatField()),
                ('drop_lng', models.FloatField()),
                ('fare_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('SEARCHING', 'Searching Driver'), ('ACCEPTED', 'Driver Accepted'), ('ARRIVED', 'Driver Arrived'), ('ONGOING', 'Ride in Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SEARCHING', max_length=20)),
                ('otp', models.CharField(blank=True, max_length=4, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides_as_driver', to='rangrago.driver')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_rider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
